__app_list:
  - name: 7zip
  - name: firefox
  - name: filezilla
  - name: irfanview
  - name: notepadplusplus
  - name: winscp
  - name: vcredist140
  - name: notepad2
  # - name: autohotkey.install
  #   version: '1.1.37.1'
