---
- name: Check if rdp_list_allowed_ips is not empty
  no_log: true
  ansible.builtin.set_fact:
    __rdp_allowed_ips: "{{ rdp_list_allowed_ips | join(',') if (rdp_list_allowed_ips is defined and rdp_list_allowed_ips | length > 0) else omit }}"

- name: Enable RDP service
  ansible.windows.win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\Terminal Server
    name: fDenyTSConnections
    data: 0
    type: dword
    state: present

- name: Set custom RDP port number
  ansible.windows.win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
    name: PortNumber
    data: "{{ rdp_port }}"
    type: dword
    state: present
  notify: Restart TermService

- name: Configure RDP TCP-IN firewall rule for custom port
  community.windows.win_firewall_rule:
    name: "RDP TCP-IN"
    localport: "{{ rdp_port }}"
    protocol: tcp
    direction: in
    action: allow
    remoteip: "{{ __rdp_allowed_ips }}"
    state: present
    enabled: true

- name: Configure RDP UDP-IN firewall rule for custom port
  community.windows.win_firewall_rule:
    name: "RDP UDP-IN"
    localport: "{{ rdp_port }}"
    protocol: udp
    direction: in
    action: allow
    remoteip: "{{ __rdp_allowed_ips }}"
    state: present
    enabled: true

- name: Ensure RDP service is running and set to automatic start
  ansible.windows.win_service:
    name: TermService
    start_mode: auto
    state: started
