---
- name: Install Remote Desktop Services
  ansible.windows.win_feature:
    name:
      - RDS-RD-Server
      - RDS-Licensing
    include_management_tools: true
    state: present
  async: 1800
  poll: 20
  register: __rds_trial_install

- name: Set the Remote Desktop licensing mode
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
    name: LicensingMode
    data: 4
    type: dword
    state: present

- name: Reboot
  ansible.windows.win_reboot:
  when: __rds_trial_install.reboot_required
