galaxy_info:
  author: "serhii9132"
  description: "Adds new users to an existing Active Directory domain"
  license: "MIT"
  min_ansible_version: "2.19"
  platforms:
    - name: Windows
      versions:
        - "2022"
        - "2025"
dependencies: []
